### ISSUE TITLE
Cannot read property 'Button' of undefined

### ISSUE THREAD

**Issue by henrikruscon** [paulgrock/hyper-touch#1]
I can't get it to work.

Cannot read property 'Button' of undefined. How did you get this to work? ✌️

**Comment by henrikruscon** [comment]
Checked electron and it seems this relies on the `touchbar` branch.

**Comment by paulgrock** [comment]
Yeah. Sorry about that. I'll make a note in the readme

**Comment by danielbayerlein** [comment]
@henrikdahl @paulgrock 

I've built Hyper with Electron v1.6.3 (includes the TouchBar) but this plugin doesn't work: `Cannot read property 'Button' of undefined`. What am I doing wrong? Any idea?

**Comment by paulgrock** [comment]
@danielbayerlein it looks like the API for creating a button changed. I'll update this in a few minutes and we'll see if that solves the problem.

**Comment by paulgrock** [comment]
@danielbayerlein I just pushed an update to match the new API. let me know if you're still running into any issues.

**Comment by danielbayerlein** [comment]
@paulgrock 

```js
const { TouchBar, TouchBarButton } = require('electron');
```

`TouchBar` and `TouchBarButton` are `undefined`

**Comment by paulgrock** [comment]
@danielbayerlein if you add `console.log(process.versions.electron)` to the plugin what version of electron does it output?

**Comment by danielbayerlein** [comment]
@paulgrock `process.versions.electron` shows `1.6.3`

**Comment by paulgrock** [comment]
@danielbayerlein hmm, not sure what the issue is. `1.6.3` should have the `TouchBar` api. If you check out the electron object does it have TouchBar on there? When you're building hyper and electron how are you doing it?

**Comment by danielbayerlein** [comment]
@paulgrock Thanks for your help!

**Hyper-Touch**

1. `cd ~/.hyper_plugins/local`
2. `git clone https://github.com/paulgrock/hyper-touch.git`
3. Add `hyper-touch` to `.hyper.js` (`localPlugins`)

**Hyper**

1. `git clone https://github.com/zeit/hyper.git`
2. `cd hyper`
3. `npm install electron@beta --save-dev`
4. `npm install`
5. `npm run dist`
6. `open dist/mac/Hyper.app`

**DevTools**

![hyper-touch](https://cloud.githubusercontent.com/assets/457834/23846724/169df0e6-07cf-11e7-8507-2ea755d6c9a7.png)
![object](https://cloud.githubusercontent.com/assets/457834/23847085/0cdaa4da-07d1-11e7-9fe4-4af1de212c88.png)

**Comment by paulgrock** [comment]
@danielbayerlein if you do `npm run app` instead of `npm run dist` does it work for you? It appears electron doesn't have the Touchbar api in the screenshot above. No idea why it doesn't since it's 1.6.3.

**Comment by danielbayerlein** [comment]
@paulgrock I found the mistake. I'll fix the error and create a PR.

**Comment by danielbayerlein** [comment]
Fixed with #3
